### ISSUE TITLE
Safe autodoc mod removes itself from world after death

### ISSUE THREAD

**Issue by BenlyAZ** [Fris0uman/Easy-CBM-Mods#4]
I have my worlds set to reset on death and for whatever reason, when they do so the safe autodoc mod is no longer active when I create a new character in them.

**Comment by Fris0uman** [comment]
Can confirm this does happen. But I have no idea what could cause it and why it would be specific to safe autodoc. Currently investigating, thanks for the report.

**Comment by BenlyAZ** [comment]
I don't know if it's specific to safe autodoc (unless you found it to be), that's just the only one of this bundle I'm using.
