### ISSUE TITLE
safe autodoc Mod does not work

### ISSUE THREAD

**Issue by Devengel** [Fris0uman/Easy-CBM-Mods#6]
just as title says, Check the save file, enter into the auto-doc and try to install the CBM in the character inventory, it should say a failure rate of 12%.
[Athalia.zip](https://github.com/Fris0uman/Easy-CBM-Mods/files/5802821/Athalia.zip)

**Comment by Fris0uman** [comment]
It seems that safe autodoc and portable autodoc are not compatible. Just use one at a time to get it to work

**Comment by Fris0uman** [comment]
Fixed by #7
